### ISSUE TITLE
Baking-Namepair-Creator 2.80

### ISSUE THREAD

**Issue by ll-Atomsk-ll** [PLyczkowski/Baking-Namepair-Creator#2]
Hello. I'm using your addon a lot it is really useful for me.  But with the resent update of bledner 2.80  it doesn't work any more. there is any chance to fix it. I tried for 20 days but I didn't know any thing of programing. Sorry if I bother you.
Thanks

**Comment by PLyczkowski** [comment]
Here is the version for Blender 2.8 - https://github.com/PLyczkowski/Baking-Namepair-Creator/blob/master/baking_namepair_creator_2_8.py
